apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: _APP_NAME-redis
  namespace: _NAMESPACE
spec:
  serviceName: _APP_NAME-redis
  replicas: 2
  selector:
    matchLabels:
      app: _APP_NAME-redis
  template:
    metadata:
      labels:
        app: _APP_NAME-redis
    spec:
      containers:
      - name: _APP_NAME-redis
        image: redis:latest
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: _APP_NAME-redis
  namespace: _NAMESPACE
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: _APP_NAME-redis
