apiVersion: v1
kind: Service
metadata:
  name: _APP_NAME
  namespace: _NAMESPACE
spec:
  selector:
    app: _APP_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
